# Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt

# Importing the dataset

In [ ]:
d1 = pd.read_csv('features.csv')
d2 = pd.read_csv('stores.csv')
d3 = pd.read_csv('train.csv')
d4 = pd.read_csv('test.csv')
d3['Date'] = pd.to_numeric(pd.to_datetime(d3['Date']))
d1['Date'] = pd.to_numeric(pd.to_datetime(d1['Date']))

In [ ]:
print(d3)

        Store  Dept                 Date  Weekly_Sales  IsHoliday
0           1     1  1265328000000000000      24924.50      False
1           1     1  1265932800000000000      46039.49       True
2           1     1  1266537600000000000      41595.55      False
3           1     1  1267142400000000000      19403.54      False
4           1     1  1267747200000000000      21827.90      False
...       ...   ...                  ...           ...        ...
421565     45    98  1348790400000000000        508.37      False
421566     45    98  1349395200000000000        628.10      False
421567     45    98  1350000000000000000       1061.02      False
421568     45    98  1350604800000000000        760.01      False
421569     45    98  1351209600000000000       1076.80      False

[421570 rows x 5 columns]


In [ ]:
merger = pd.merge(d3, d1)
x = pd.merge(merger, d2)
x.shape

(421570, 16)

In [ ]:
print(x.head())

   Store  Dept                 Date  Weekly_Sales  IsHoliday  Temperature  \
0      1     1  1265328000000000000      24924.50      False        42.31   
1      1     2  1265328000000000000      50605.27      False        42.31   
2      1     3  1265328000000000000      13740.12      False        42.31   
3      1     4  1265328000000000000      39954.04      False        42.31   
4      1     5  1265328000000000000      32229.38      False        42.31   

   Fuel_Price  MarkDown1  MarkDown2  MarkDown3  MarkDown4  MarkDown5  \
0       2.572        NaN        NaN        NaN        NaN        NaN   
1       2.572        NaN        NaN        NaN        NaN        NaN   
2       2.572        NaN        NaN        NaN        NaN        NaN   
3       2.572        NaN        NaN        NaN        NaN        NaN   
4       2.572        NaN        NaN        NaN        NaN        NaN   

          CPI  Unemployment Type    Size  
0  211.096358         8.106    A  151315  
1  211.096358     

#Data Preprocessing

Label Encoding of Categorical Data

In [ ]:
print(x)

        Store  Dept                 Date  Weekly_Sales  IsHoliday  \
0           1     1  1265328000000000000      24924.50      False   
1           1     2  1265328000000000000      50605.27      False   
2           1     3  1265328000000000000      13740.12      False   
3           1     4  1265328000000000000      39954.04      False   
4           1     5  1265328000000000000      32229.38      False   
...       ...   ...                  ...           ...        ...   
421565     45    93  1351209600000000000       2487.80      False   
421566     45    94  1351209600000000000       5203.31      False   
421567     45    95  1351209600000000000      56017.47      False   
421568     45    97  1351209600000000000       6817.48      False   
421569     45    98  1351209600000000000       1076.80      False   

        Temperature  Fuel_Price  MarkDown1  MarkDown2  MarkDown3  MarkDown4  \
0             42.31       2.572        NaN        NaN        NaN        NaN   
1            

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [14])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 [1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 [1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 ...
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 7] = le.fit_transform(x[:, 7])

In [ ]:
print(x[100:, 7])

[1 1 1 ... 0 0 0]


In [ ]:
print(x.shape)

(421570, 18)


#Splitting the dataset

In [ ]:
y = x[:, (6)]
x = x[:, (0, 1, 2, 3, 4, 5, 7, 8, 9, 15, 16, 17)]
print(y)
print(x[:5 , :])

[24924.5 50605.27 13740.12 ... 56017.47 6817.48 1076.8]
[[1.0 0.0 0.0 1 1 1265328000000000000 0 42.31 2.572 211.0963582 8.106
  151315]
 [1.0 0.0 0.0 1 2 1265328000000000000 0 42.31 2.572 211.0963582 8.106
  151315]
 [1.0 0.0 0.0 1 3 1265328000000000000 0 42.31 2.572 211.0963582 8.106
  151315]
 [1.0 0.0 0.0 1 4 1265328000000000000 0 42.31 2.572 211.0963582 8.106
  151315]
 [1.0 0.0 0.0 1 5 1265328000000000000 0 42.31 2.572 211.0963582 8.106
  151315]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 ... 218.9551002 7.244 184109]
 [0.0 1.0 0.0 ... 127.1917742 6.866 93188]
 [1.0 0.0 0.0 ... 126.0766452 7.372 205863]
 ...
 [1.0 0.0 0.0 ... 197.6063534 8.09 203007]
 [1.0 0.0 0.0 ... 126.5782857 13.975 206302]
 [1.0 0.0 0.0 ... 131.1930968 5.621 219622]]


In [ ]:
print(y_train)

[6976.9 61958.93 30029.99 ... 13742.09 31969.84 7314.91]


#Building the Regression Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

#Predicting the weekly sales for test set

In [ ]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[2017.78 2500.16]
 [27325.333999999995 47129.06]
 [487.5200000000001 484.0]
 ...
 [22925.026000000005 24321.74]
 [1193.95 879.8]
 [20578.153 23177.4]]


#Checking accuracy

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9494136367127481