#Importing Libraries

In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd

#Importing the dataset

In [ ]:
features = pd.read_csv('features.csv')
stores = pd.read_csv('stores.csv')
training = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

#Data Preprocessing

Imputing the missing values

In [ ]:
mask = features['CPI'].isnull()
features['CPI'].fillna(method = 'ffill', inplace = True)
features['Unemployment'].fillna(method = 'ffill', inplace = True)

In [ ]:
features.iloc[169]

Store                    1
Date            2013-05-03
Temperature          66.66
Fuel_Price           3.386
MarkDown1          2298.63
MarkDown2              2.0
MarkDown3            129.9
MarkDown4            55.46
MarkDown5          1301.04
CPI              225.17016
Unemployment         6.314
IsHoliday            False
Name: 169, dtype: object

In [ ]:
features.iloc[357]

Store                    2
Date            2013-06-14
Temperature          80.91
Fuel_Price           3.431
MarkDown1           9784.1
MarkDown2           548.27
MarkDown3            674.6
MarkDown4          2966.31
MarkDown5          5282.33
CPI             224.802531
Unemployment         6.112
IsHoliday            False
Name: 357, dtype: object

Converting Date string to datetime

In [ ]:
features['Date'] = pd.to_datetime(features['Date'])
training['Date'] = pd.to_datetime(training['Date'])
test['Date'] = pd.to_datetime(test['Date'])

Imputing missing values for the markdowns

In [ ]:
cutoff_date = pd.to_datetime('11/11/2011')  # Replace 'yyyy-mm-dd' with the actual date

# Calculate the mean of the known values store-wise
store_means1 = features[features['Date'] > cutoff_date].groupby('Store')['MarkDown1'].mean()

# Create a dictionary to map store-wise means to their respective stores
store_means_dict1 = store_means1.to_dict()

# Impute missing values with the store-wise means
features['MarkDown1'] = features.apply(lambda row: row['MarkDown1'] if pd.notnull(row['MarkDown1']) else store_means_dict1.get(row['Store']) , axis=1)

In [ ]:
cutoff_date = pd.to_datetime('11/11/2011')  # Replace 'yyyy-mm-dd' with the actual date

# Calculate the mean of the known values store-wise
store_means2 = features[features['Date'] > cutoff_date].groupby('Store')['MarkDown2'].mean()

# Create a dictionary to map store-wise means to their respective stores
store_means_dict2 = store_means2.to_dict()

# Impute missing values with the store-wise means
features['MarkDown2'] = features.apply(lambda row: row['MarkDown2'] if pd.notnull(row['MarkDown2']) else store_means_dict2.get(row['Store']) , axis=1)

In [ ]:
cutoff_date = pd.to_datetime('11/11/2011')  # Replace 'yyyy-mm-dd' with the actual date

# Calculate the mean of the known values store-wise
store_means3 = features[features['Date'] > cutoff_date].groupby('Store')['MarkDown3'].mean()

# Create a dictionary to map store-wise means to their respective stores
store_means_dict3 = store_means3.to_dict()

# Impute missing values with the store-wise means
features['MarkDown3'] = features.apply(lambda row: row['MarkDown3'] if pd.notnull(row['MarkDown3']) else store_means_dict3.get(row['Store']) , axis=1)

In [ ]:
cutoff_date = pd.to_datetime('11/11/2011')  # Replace 'yyyy-mm-dd' with the actual date

# Calculate the mean of the known values store-wise
store_means4 = features[features['Date'] > cutoff_date].groupby('Store')['MarkDown4'].mean()

# Create a dictionary to map store-wise means to their respective stores
store_means_dict4 = store_means4.to_dict()

# Impute missing values with the store-wise means
features['MarkDown4'] = features.apply(lambda row: row['MarkDown4'] if pd.notnull(row['MarkDown4']) else store_means_dict4.get(row['Store']) , axis=1)

In [ ]:
cutoff_date = pd.to_datetime('11/11/2011')  # Replace 'yyyy-mm-dd' with the actual date

# Calculate the mean of the known values store-wise
store_means5 = features[features['Date'] > cutoff_date].groupby('Store')['MarkDown5'].mean()

# Create a dictionary to map store-wise means to their respective stores
store_means_dict5 = store_means5.to_dict()

# Impute missing values with the store-wise means
features['MarkDown5'] = features.apply(lambda row: row['MarkDown5'] if pd.notnull(row['MarkDown5']) else store_means_dict5.get(row['Store']) , axis=1)

In [ ]:
features.iloc[10]

Store                             1
Date            2010-04-16 00:00:00
Temperature                   66.32
Fuel_Price                    2.808
MarkDown1               8515.847753
MarkDown2               3307.939861
MarkDown3               1687.340341
MarkDown4               3667.642809
MarkDown5               4404.452472
CPI                        210.4887
Unemployment                  7.808
IsHoliday                     False
Name: 10, dtype: object

Converting datetime to numeric field

In [ ]:
features['Date'] = pd.to_numeric(features['Date'])
training['Date'] = pd.to_numeric(training['Date'])
test['Date'] = pd.to_numeric(test['Date'])

Merging datasets

In [ ]:
merger1 = pd.merge(training, features)
merger2 = pd.merge(merger1, stores)
merger3 = pd.merge(test, features)
merger4 = pd.merge(merger3, stores)

In [ ]:
print(merger2)

        Store  Dept                 Date  Weekly_Sales  IsHoliday  \
0           1     1  1265328000000000000      24924.50      False   
1           1     2  1265328000000000000      50605.27      False   
2           1     3  1265328000000000000      13740.12      False   
3           1     4  1265328000000000000      39954.04      False   
4           1     5  1265328000000000000      32229.38      False   
...       ...   ...                  ...           ...        ...   
421565     45    93  1351209600000000000       2487.80      False   
421566     45    94  1351209600000000000       5203.31      False   
421567     45    95  1351209600000000000      56017.47      False   
421568     45    97  1351209600000000000       6817.48      False   
421569     45    98  1351209600000000000       1076.80      False   

        Temperature  Fuel_Price    MarkDown1    MarkDown2    MarkDown3  \
0             42.31       2.572  8515.847753  3307.939861  1687.340341   
1             42.31    

In [ ]:
print(merger4)

        Store  Dept                 Date  IsHoliday  Temperature  Fuel_Price  \
0           1     1  1351814400000000000      False        55.32       3.386   
1           1     2  1351814400000000000      False        55.32       3.386   
2           1     3  1351814400000000000      False        55.32       3.386   
3           1     4  1351814400000000000      False        55.32       3.386   
4           1     5  1351814400000000000      False        55.32       3.386   
...       ...   ...                  ...        ...          ...         ...   
115059     45    93  1374796800000000000      False        76.06       3.804   
115060     45    94  1374796800000000000      False        76.06       3.804   
115061     45    95  1374796800000000000      False        76.06       3.804   
115062     45    97  1374796800000000000      False        76.06       3.804   
115063     45    98  1374796800000000000      False        76.06       3.804   

        MarkDown1  MarkDown2  MarkDown3

Encoding Categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct1 = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [14])], remainder = 'passthrough')
ct2 = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [13])], remainder = 'passthrough')
merger2 = np.array(ct1.fit_transform(merger2))
merger4 = np.array(ct2.fit_transform(merger4))

In [ ]:
print(merger2)

[[1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 [1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 [1.0 0.0 0.0 ... 211.0963582 8.106 151315]
 ...
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]
 [0.0 1.0 0.0 ... 192.3088989 8.667 118221]]


In [ ]:
print(merger4)

[[1.0 0.0 0.0 ... 223.4627793 6.573 151315]
 [1.0 0.0 0.0 ... 223.4627793 6.573 151315]
 [1.0 0.0 0.0 ... 223.4627793 6.573 151315]
 ...
 [0.0 1.0 0.0 ... 193.589304 8.335 118221]
 [0.0 1.0 0.0 ... 193.589304 8.335 118221]
 [0.0 1.0 0.0 ... 193.589304 8.335 118221]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
merger2[:, 7] = le.fit_transform(merger2[:, 7])
merger4[:, 6] = le.fit_transform(merger4[:, 6])

In [ ]:
print(merger2[:5, :])

[[1.0 0.0 0.0 1 1 1265328000000000000 24924.5 0 42.31 2.572
  8515.847752808988 3307.9398611111114 1687.340340909091
  3667.6428089887645 4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 2 1265328000000000000 50605.27 0 42.31 2.572
  8515.847752808988 3307.9398611111114 1687.340340909091
  3667.6428089887645 4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 3 1265328000000000000 13740.12 0 42.31 2.572
  8515.847752808988 3307.9398611111114 1687.340340909091
  3667.6428089887645 4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 4 1265328000000000000 39954.04 0 42.31 2.572
  8515.847752808988 3307.9398611111114 1687.340340909091
  3667.6428089887645 4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 5 1265328000000000000 32229.38 0 42.31 2.572
  8515.847752808988 3307.9398611111114 1687.340340909091
  3667.6428089887645 4404.452471910113 211.0963582 8.106 151315]]


In [ ]:
print(merger4[:5, :])

[[1.0 0.0 0.0 1 1 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 2 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 3 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 4 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 5 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]]


#Splitting the dataset into x and y

In [ ]:
x_train = merger2[:, (0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17)]
y_train = merger2[:, 6]

In [ ]:
print(x_train[:5, :])

[[1.0 0.0 0.0 1 1 1265328000000000000 0 42.31 2.572 8515.847752808988
  3307.9398611111114 1687.340340909091 3667.6428089887645
  4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 2 1265328000000000000 0 42.31 2.572 8515.847752808988
  3307.9398611111114 1687.340340909091 3667.6428089887645
  4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 3 1265328000000000000 0 42.31 2.572 8515.847752808988
  3307.9398611111114 1687.340340909091 3667.6428089887645
  4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 4 1265328000000000000 0 42.31 2.572 8515.847752808988
  3307.9398611111114 1687.340340909091 3667.6428089887645
  4404.452471910113 211.0963582 8.106 151315]
 [1.0 0.0 0.0 1 5 1265328000000000000 0 42.31 2.572 8515.847752808988
  3307.9398611111114 1687.340340909091 3667.6428089887645
  4404.452471910113 211.0963582 8.106 151315]]


In [ ]:
print(y_train)

[24924.5 50605.27 13740.12 ... 56017.47 6817.48 1076.8]


In [ ]:
x_test = merger4[:, :]

In [ ]:
print(x_test[:5, :])

[[1.0 0.0 0.0 1 1 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 2 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 3 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 4 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]
 [1.0 0.0 0.0 1 5 1351814400000000000 0 55.32 3.386 6766.44 5147.7 50.82
  3639.9 2737.42 223.4627793 6.573 151315]]


#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] = sc.fit_transform(x_train[:, 5:])
x_test[:, 5:] = sc.transform(x_test[:, 5:])

#Building the Regression Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

#Predicting values for the test set

In [ ]:
y_test = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(y_test)

[27398.08 48051.49 10726.08 ... 55458.38  6515.06   799.41]
